language: node_js
node_js:
  - "node"
script:
  # Compile and lint code
  - yarn run vscode:prepublish
  - yarn run lint
cache:
  yarn: true
# Don't send mails, I'm using ccmenu
notifications:
  email: false
